//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TPTModel", "FK_Sentient_AllegianceID", "Allegiance", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TPTConsole.Model.Allegiance), "Sentient", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TPTConsole.Model.Sentient), true)]

#endregion

namespace TPTConsole.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TPTEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TPTEntities object using the connection string found in the 'TPTEntities' section of the application configuration file.
        /// </summary>
        public TPTEntities() : base("name=TPTEntities", "TPTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TPTEntities object.
        /// </summary>
        public TPTEntities(string connectionString) : base(connectionString, "TPTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TPTEntities object.
        /// </summary>
        public TPTEntities(EntityConnection connection) : base(connection, "TPTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Sentient> Sentients
        {
            get
            {
                if ((_Sentients == null))
                {
                    _Sentients = base.CreateObjectSet<Sentient>("Sentients");
                }
                return _Sentients;
            }
        }
        private ObjectSet<Sentient> _Sentients;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Allegiance> Allegiances
        {
            get
            {
                if ((_Allegiances == null))
                {
                    _Allegiances = base.CreateObjectSet<Allegiance>("Allegiances");
                }
                return _Allegiances;
            }
        }
        private ObjectSet<Allegiance> _Allegiances;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sentients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSentients(Sentient sentient)
        {
            base.AddObject("Sentients", sentient);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Allegiances EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAllegiances(Allegiance allegiance)
        {
            base.AddObject("Allegiances", allegiance);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TPTModel", Name="Allegiance")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Allegiance : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Allegiance object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Allegiance CreateAllegiance(global::System.Int32 id)
        {
            Allegiance allegiance = new Allegiance();
            allegiance.ID = id;
            return allegiance;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TPTModel", "FK_Sentient_AllegianceID", "Sentient")]
        public EntityCollection<Sentient> Sentients
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Sentient>("TPTModel.FK_Sentient_AllegianceID", "Sentient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Sentient>("TPTModel.FK_Sentient_AllegianceID", "Sentient", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TPTModel", Name="Droid")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Droid : Sentient
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Droid object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Droid CreateDroid(global::System.Int32 id)
        {
            Droid droid = new Droid();
            droid.ID = id;
            return droid;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DroidType
        {
            get
            {
                return _DroidType;
            }
            set
            {
                OnDroidTypeChanging(value);
                ReportPropertyChanging("DroidType");
                _DroidType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DroidType");
                OnDroidTypeChanged();
            }
        }
        private global::System.String _DroidType;
        partial void OnDroidTypeChanging(global::System.String value);
        partial void OnDroidTypeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TPTModel", Name="Jedi")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Jedi : Sentient
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Jedi object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Jedi CreateJedi(global::System.Int32 id)
        {
            Jedi jedi = new Jedi();
            jedi.ID = id;
            return jedi;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LightsaberColor
        {
            get
            {
                return _LightsaberColor;
            }
            set
            {
                OnLightsaberColorChanging(value);
                ReportPropertyChanging("LightsaberColor");
                _LightsaberColor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LightsaberColor");
                OnLightsaberColorChanged();
            }
        }
        private global::System.String _LightsaberColor;
        partial void OnLightsaberColorChanging(global::System.String value);
        partial void OnLightsaberColorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MidichlorianCount
        {
            get
            {
                return _MidichlorianCount;
            }
            set
            {
                OnMidichlorianCountChanging(value);
                ReportPropertyChanging("MidichlorianCount");
                _MidichlorianCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MidichlorianCount");
                OnMidichlorianCountChanged();
            }
        }
        private Nullable<global::System.Int32> _MidichlorianCount;
        partial void OnMidichlorianCountChanging(Nullable<global::System.Int32> value);
        partial void OnMidichlorianCountChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TPTModel", Name="Other")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Other : Sentient
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Other object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Other CreateOther(global::System.Int32 id)
        {
            Other other = new Other();
            other.ID = id;
            return other;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsMale
        {
            get
            {
                return _IsMale;
            }
            set
            {
                OnIsMaleChanging(value);
                ReportPropertyChanging("IsMale");
                _IsMale = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsMale");
                OnIsMaleChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsMale;
        partial void OnIsMaleChanging(Nullable<global::System.Boolean> value);
        partial void OnIsMaleChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TPTModel", Name="Sentient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(Droid))]
    [KnownTypeAttribute(typeof(Jedi))]
    [KnownTypeAttribute(typeof(Other))]
    public partial class Sentient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Sentient object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Sentient CreateSentient(global::System.Int32 id)
        {
            Sentient sentient = new Sentient();
            sentient.ID = id;
            return sentient;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AllegianceID
        {
            get
            {
                return _AllegianceID;
            }
            set
            {
                OnAllegianceIDChanging(value);
                ReportPropertyChanging("AllegianceID");
                _AllegianceID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AllegianceID");
                OnAllegianceIDChanged();
            }
        }
        private Nullable<global::System.Int32> _AllegianceID;
        partial void OnAllegianceIDChanging(Nullable<global::System.Int32> value);
        partial void OnAllegianceIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TPTModel", "FK_Sentient_AllegianceID", "Allegiance")]
        public Allegiance Allegiance
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Allegiance>("TPTModel.FK_Sentient_AllegianceID", "Allegiance").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Allegiance>("TPTModel.FK_Sentient_AllegianceID", "Allegiance").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Allegiance> AllegianceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Allegiance>("TPTModel.FK_Sentient_AllegianceID", "Allegiance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Allegiance>("TPTModel.FK_Sentient_AllegianceID", "Allegiance", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
